# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DINGE' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DINGE

  pod 'YYKit', '~> 1.0.7'
  pod 'SDCycleScrollView','~> 1.65'
  pod 'SDAutoLayout', '~> 2.1.7'
  pod 'FDFullscreenPopGesture', '~> 1.1'

  target 'DINGETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DINGEUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
